export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'

export const SET_EDIT_JOB = 'SET_EDIT_JOB'

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN'

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN'
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'

export const SHARE_JOB_BEGIN = 'SHARE_JOB_BEGIN'
export const SHARE_JOB_SUCCESS = 'SHARE_JOB_SUCCESS'
export const SHARE_JOB_ERROR = 'SHARE_JOB_ERROR'

export const CREATE_TASK_BEGIN = 'CREATE_TASK_BEGIN'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'

export const GET_TASKS_BEGIN = 'GET_TASKS_BEGIN'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'

export const SET_CHECK_TASK = 'SET_CHECK_TASK'

export const UPDATE_TASK_BEGIN = 'UPDATE_TASK_BEGIN'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR'

export const DELETE_TASK_BEGIN = 'DELETE_TASK_BEGIN'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_ERROR = 'UPDATE_TASK_ERROR'

export const LIST_TITLE_BEGIN = 'LIST_TITLE_BEGIN'
export const LIST_TITLE_SUCCESS = 'LIST_TITTLE_SUCCESS'
export const LIST_TITLE_ERROR = 'LIST_TITLE_ERROR'

export const DUPLICATE_LIST_BEGIN = 'DUPLICATE_LIST_BEGIN'
export const DUPLICATE_LIST_SUCCESS = 'DUPLICATE_LIST_SUCCESS'
export const DUPLICATE_LIST_ERROR = 'DUPLICATE_LIST_ERROR'